language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "build"
script:
  - npm run build
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  committer_from_gh: true
  on:
    branch: master
